### ISSUE TITLE
Update package.json to make "npm install" works

### ISSUE THREAD

**Issue by dev-andreavendrame** [alastria/alastria-identity-example#144]
Clone the repository and install the dependencies with `npm install` now doens't work.
Please update the package because the libraries https://github.com/alastria/alastria-identity-lib and https://github.com/alastria/alastria-identity-JSON-objects aren't included automatically.

**Comment by rober12** [comment]
Hello @dev-andreavendrame 

With which version of node and npm is `npm install` not working for you?

I just tried it with the following versions and it worked correctly:
- node -> v16.13.0
- npm -> v8.15.0

Greetings.

**Comment by dev-andreavendrame** [comment]
Hi @rober12 

I've tried with:
- Node v16.15.1
- npm 6.14.17

Is there any bug reported for these versions?

**Comment by rober12** [comment]
Good morning @dev-andreavendrame ,

I don't know how you installed node and npm, but I recommend you to install them with nvm. Once you have nvm installed, just run `nvm install v16` or whatever version you want.

It has been detected that if you don't install with nvm, it can give failures, because nvm installs both node and the version of npm that goes hand in hand with the version of node you want to install. 

Try that and let us know if it works for you. 

Best regards.

**Comment by dev-andreavendrame** [comment]
Thanks for your help, I'll try and let you know.

Have a good day.

**Comment by dev-andreavendrame** [comment]
Good afternoon.
I've tried the solution that you suggested me, but it doesn't work.
Maybe you have any other ones?

**Comment by rober12** [comment]
Good Afternoon,

Try node version 14, no problems have been reported with that one.

However, I don't understand how you can run the examples if npm install didn't work for you.

Best regards

**Comment by dev-andreavendrame** [comment]
Personally I don't understand why `npm install` doesn't work with the actual package.json file, but I've tried in this way:

1. Clone the repository
2. Run `npm install`
3. Run `npm install alastria-identity-lib`

This way has worked for me, but trying to add the Github libraries in different ways didn't work...

BTW thanks!
