### ISSUE TITLE
Cannot complete the execution of exampleFirstEntity folder files

### ISSUE THREAD

**Issue by dev-andreavendrame** [alastria/alastria-identity-example#146]
Good afternoon!

We are working with Trublo for a project that needs to use the Alastria blockchain.
We have been whitelisted for using the Network B node for Trublo projects http://54.195.253.191:8545.
We have also been whitelisted to use a static IP of one of our server and we are sending calls from this IP.

Now we are trying to execute the files contained in the alastria/alastria-identity-example (branch https://github.com/alastria/alastria-identity-example/tree/v2.0.0).

We have success in calling the authentication.js (main folder) and we have tried to execute in order the files in the [exampleFirstEntity](https://github.com/alastria/alastria-identity-example/tree/v2.0.0/exampleFirstEntity) folder.

The execution of the first file ([1.createEntityAlastriaID.js](https://github.com/alastria/alastria-identity-example/blob/v2.0.0/exampleFirstEntity/1.createEntityAlastriaID.js)) is successful, but the second has not.

This is the error that we are getting when we use the command `node 2.addEntity.js` from inside the folder.

<img width="640" alt="Screenshot 2023-01-20 alle 16 53 57" src="https://user-images.githubusercontent.com/118825602/213750234-2a9b18b0-2932-4900-98df-84e07ed3a3eb.png">

We have tried to adapt the configuration.json file with our information (replacing the "nodeURL": "http://63.33.206.111/rpc", with our URL and port **http://54.195.253.191:8545**) but we still get errors.
We are not sure to be connected to the RedB network.

What do we need to do in order to solve the problem and be sure to be connected to the right network since it isn't specified in the repository?

Thanks in advance.
Best regards,

Andrea Vendrame.

**Comment by rober12** [comment]
Good afternoon

To make use of the smart contracts deployed in the B-network I recommend you to do the following apart from using the IP of the node you mentioned.

You have to take the addresses located in the file https://github.com/alastria/alastriaID-truffle-contracts/blob/v2.0.0/addresses-b.json and introduce them in the following config.js file located in the following path alastria-identity-example/node_modules/alastria-identity-lib/dist
![imagen](https://user-images.githubusercontent.com/17437316/214603303-ca3c53fa-211d-4dfc-bde8-54c4ca70547b.png)

With this plus the node you will be making use of the smart contracts deployed in the B network.

On the other hand, you are making use of your own keystore for testing, right?

If so, check where in the configuration.json you are writing the new DID that you have created by executing example 1, because in example 2, which is the one that is failing, in the line https://github.com/alastria/alastria-identity-example/blob/master/exampleFirstEntity/2.addEntity.js#L41 you should put the DID that you have created after executing the first example.

Best regards.

**Comment by dev-andreavendrame** [comment]
Good morning.

We don't know how to connect to the Red-B network.
We have been told that we need to connect to the Trublo Alastria node (for this reason we have whitelisted our server IP).
We need to use the Red-B network, but we don't know how to connect and test our calls to the node.
Can you help us to setup the keystore and configuration file in order to do everything in the proper way please?
P.S. Does a block explorer exists for Red-B and Red-T network?

Best regards.

**Comment by irzinfante** [comment]
Connection to the network has nothing to do with the usage of Alastria ID. If you encounter any issue connecting to "your" node, this is not the place for that. You can reach me by email: iker@alastria.io

**Comment by rober12** [comment]
Good morning @dev-andreavendrame,

Can this issue be closed?

Greetings and thanks in advance.

**Comment by dev-andreavendrame** [comment]
Yeah, I close it.
Thanks for your availability.
