### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by dev-andreavendrame** [alastria/alastria-identity-example#150]
Good afternoon @rober12 .
In some examples the public key of an entity is used.
For example, in the config.json file there is this line and obviously there are the related public key for the other identities:

"entity2Pubk": "0xa33e56a80b9dc83a4456265d877c0765cea76146e625572fc679804f8867222ca3c816433a9b6e6690b0b8e919ffa874982706e812314aae09d85fc62fc4fa3c"

My question is the following. What is the meaning of the value of "entity2Pubk"? It is not a wallet since it is too long, so what is it?

Thanks and have a good day,

Andrea.

**Comment by rober12** [comment]
Good morning @dev-andreavendrame,

The entity2Pubk value refers to the public key of entity 2 in this case. This value is used in the model to check the signatures of the objects that should be exchanged between users and entities when issuing credentials, delivering presentations, euthenticating and creating identities. 

This process of exchanging objects between an entity and a subject is not reflected in the examples since everything is executed on the same machine, but keep in mind that the communication protocol between an entity and a subject is always the same except for identity creation where the object used is different. As I mentioned before, this protocol is specified in the following diagram: https://raw.githubusercontent.com/alastria/alastria-identity/master/docs/img/US-2.1.1%20Alastria%20ID%20Authentication.png

It should be noted that in each object exchange both the entity and the subject check the signature of the object sent by the other party and for this purpose they use the **public key**.

Best regards and have a good day.

**Comment by dev-andreavendrame** [comment]
Ok thanks, it is more clear now.
In this case the public key of the entity 2 is something derived from the wallet address or it is a kay that belongs to another pair of private-public key that is used in a traditional way?

**Comment by rober12** [comment]
Good morning @dev-andreavendrame , 

The wallets used right now are wallets that contain a keystore. From that keystore both the public key and the private key are derived. 
This keystore contains a series of parameters that interact with each other in a complex way and a field called address which is the EOA(external owned account) of that keystore and therefore of the wallet.

![image](https://user-images.githubusercontent.com/17437316/218412174-91da4faa-b83f-4a14-ae1a-9225c323e23c.png)

With the help of some libraries, the keystore is interacted with this parameters and these values(publicKey and privateKey) are obtained.

Greetings.

**Comment by dev-andreavendrame** [comment]
Perfect, all clear now.
Thank you for your availability!
Best regards,

Andrea.
